# Generated by Django 2.0.4 on 2018-04-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated time')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted time')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('value', models.TextField(blank=True, db_index=True, default='', null=True, verbose_name='Value')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
