# Generated by Django 2.0.4 on 2018-10-22 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hhcms.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181021_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated time')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted time')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', hhcms.apps.account.models.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Cellphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', related_query_name='property', to=settings.AUTH_USER_MODEL),
        ),
    ]
