# Generated by Django 2.0.4 on 2018-10-22 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181022_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['id'], 'verbose_name': 'property', 'verbose_name_plural': 'Properties'},
        ),
    ]
